/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.project.view.form;

import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;
import ps.project.controller.Controller;
import ps.project.domain.Automobile;
import ps.project.domain.Currency;
import ps.project.domain.Fuel;
import ps.project.domain.Model;
import ps.project.domain.VechileType;

/**
 *
 * @author saska
 */
public class FrmAutomobile extends javax.swing.JDialog {

    /**
     * Creates new form FrmAutomobile
     */
    public FrmAutomobile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        cbModel = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblCubicCapacity = new javax.swing.JLabel();
        txtCubicCapacity = new javax.swing.JTextField();
        lblEnginePower = new javax.swing.JLabel();
        txtEnginePower = new javax.swing.JTextField();
        lblPriceWithWat = new javax.swing.JLabel();
        txtPriceWithWat = new javax.swing.JTextField();
        lblPriceWithoutWat = new javax.swing.JLabel();
        txtPriceWithoutWat = new javax.swing.JTextField();
        lblVechileType = new javax.swing.JLabel();
        cbVechileType = new javax.swing.JComboBox<>();
        lblFuel = new javax.swing.JLabel();
        cbFuel = new javax.swing.JComboBox<>();
        lblCurrency = new javax.swing.JLabel();
        cbCurrency = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Automobil:"));

        lblId.setText("Id:");

        lblModel.setText("Model:");

        cbModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModelActionPerformed(evt);
            }
        });

        lblCubicCapacity.setText("Zapremina motora:");

        lblEnginePower.setText("Snaga motora (KS):");

        txtEnginePower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnginePowerActionPerformed(evt);
            }
        });

        lblPriceWithWat.setText("Cena sa PDV-om:");

        txtPriceWithWat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceWithWatActionPerformed(evt);
            }
        });

        lblPriceWithoutWat.setText("Cena bez PDV-a:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblCubicCapacity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCubicCapacity))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblEnginePower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEnginePower, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblPriceWithWat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceWithWat))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblPriceWithoutWat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPriceWithoutWat))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCubicCapacity)
                    .addComponent(txtCubicCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnginePower)
                    .addComponent(txtEnginePower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceWithWat)
                    .addComponent(txtPriceWithWat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceWithoutWat)
                    .addComponent(txtPriceWithoutWat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblVechileType.setText("Karoserija:");

        lblFuel.setText("Gorivo:");

        cbFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuelActionPerformed(evt);
            }
        });

        lblCurrency.setText("Valuta:");

        btnSave.setText("Sačuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblId)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblModel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbModel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblVechileType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbVechileType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCurrency)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblFuel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel)
                    .addComponent(cbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVechileType)
                    .addComponent(cbVechileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuel)
                    .addComponent(cbFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurrency)
                    .addComponent(cbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(123, 123, 123))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModelActionPerformed

    private void txtEnginePowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnginePowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnginePowerActionPerformed

    private void txtPriceWithWatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceWithWatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceWithWatActionPerformed

    private void cbFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        /*Automobile automobile= new Automobile();
        automobile.setAutomobileId(Long.parseLong(txtId.getText().trim()));
        automobile.setModelId(new Long(cbModel.getSelectedIndex()));
        automobile.setCubicCapacity(Long.parseLong(txtCubicCapacity.getText().trim()));
        automobile.setEnginePower(Long.parseLong(txtEnginePower.getText().trim()));
        automobile.setPriceWithWat(new BigDecimal(txtPriceWithWat.getText().trim()));
        automobile.setPriceWithoutWat(new BigDecimal(txtPriceWithoutWat.getText().trim()));
        automobile.setVechileType((VechileType) cbVechileType.getSelectedItem());
        automobile.setFuel((Fuel) cbFuel.getSelectedItem());
        automobile.setCurrency((Currency) cbCurrency.getSelectedItem());
        
        Controller controller = Controller.getInstance();
       // controller.addAutomobile(automobile);
        JOptionPane.showMessageDialog(this, "Automobil je uspešno sačuvan!");*/
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cbCurrency;
    private javax.swing.JComboBox<Object> cbFuel;
    private javax.swing.JComboBox<Object> cbModel;
    private javax.swing.JComboBox<Object> cbVechileType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCubicCapacity;
    private javax.swing.JLabel lblCurrency;
    private javax.swing.JLabel lblEnginePower;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblPriceWithWat;
    private javax.swing.JLabel lblPriceWithoutWat;
    private javax.swing.JLabel lblVechileType;
    private javax.swing.JTextField txtCubicCapacity;
    private javax.swing.JTextField txtEnginePower;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPriceWithWat;
    private javax.swing.JTextField txtPriceWithoutWat;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        setLocationRelativeTo(null);
      /*  fillCbModel(); 
        fillCbVechileType();
        fillCbFuel();
        fillCbCurrency();*/
   }

  /*  private void fillCbModel() {
        cbModel.removeAllItems();
        List<Model> models = Controller.getInstance().getAllModels();
        for (Model model : models) {
            cbModel.addItem(model);
        }

    }

    private void fillCbVechileType() {
        cbVechileType.removeAllItems();
        for (VechileType vechileType : VechileType.values()) {
            cbVechileType.addItem(vechileType);
        }
    }

    private void fillCbFuel() {
        cbFuel.removeAllItems();
        for (Fuel fuel : Fuel.values()) {
            cbFuel.addItem(fuel);
        }
    }

    private void fillCbCurrency() {
       cbCurrency.removeAllItems();
        for (Currency currency : Currency.values()) {
            cbCurrency.addItem(currency);
        }
    }*/
}
