/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.project.view.form;

import javax.swing.JDialog;
import javax.swing.JFrame;
import ps.project.controller.Controller;

/**
 *
 * @author saska
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        prepareView();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblimgHolder = new javax.swing.JLabel();
        lblSuccesfulLoginMessage = new javax.swing.JLabel();
        lblLoggedUser = new javax.swing.JLabel();
        txtLoggedUser = new javax.swing.JTextField();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuCustomer = new javax.swing.JMenu();
        jmiNewCustomer = new javax.swing.JMenuItem();
        jmiShowAllCustomers = new javax.swing.JMenuItem();
        jMenuAutomobile = new javax.swing.JMenu();
        jmiNewAutomobile = new javax.swing.JMenuItem();
        jmiShowAllAutomobiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Početna ");
        setSize(new java.awt.Dimension(1000, 640));

        lblimgHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblimgHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ps/project/img/imgMain.png"))); // NOI18N

        lblSuccesfulLoginMessage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSuccesfulLoginMessage.setText(" Uspešna prijava na sistem!");

        lblLoggedUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoggedUser.setText("Prijavljeni korisnik:");

        txtLoggedUser.setEditable(false);
        txtLoggedUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLoggedUser.setText(" ");

        jMenuBarMain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jMenuCustomer.setText("Kupac");

        jmiNewCustomer.setText("Novi kupac");
        jmiNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewCustomerActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jmiNewCustomer);

        jmiShowAllCustomers.setText("Prikaz kupaca");
        jmiShowAllCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowAllCustomersActionPerformed(evt);
            }
        });
        jMenuCustomer.add(jmiShowAllCustomers);

        jMenuBarMain.add(jMenuCustomer);

        jMenuAutomobile.setText("Automobil");
        jMenuAutomobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAutomobileActionPerformed(evt);
            }
        });

        jmiNewAutomobile.setText("Novi automobil");
        jmiNewAutomobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNewAutomobileActionPerformed(evt);
            }
        });
        jMenuAutomobile.add(jmiNewAutomobile);

        jmiShowAllAutomobiles.setText("Prikaz automobila");
        jmiShowAllAutomobiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowAllAutomobilesActionPerformed(evt);
            }
        });
        jMenuAutomobile.add(jmiShowAllAutomobiles);

        jMenuBarMain.add(jMenuAutomobile);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblimgHolder)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLoggedUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoggedUser)))
                .addGap(334, 334, 334))
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(lblSuccesfulLoginMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblimgHolder)
                .addGap(40, 40, 40)
                .addComponent(lblSuccesfulLoginMessage)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoggedUser)
                    .addComponent(txtLoggedUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewCustomerActionPerformed
        JDialog frmCustomer= new FrmCustomer(this, true);
        frmCustomer.setVisible(true);
    }//GEN-LAST:event_jmiNewCustomerActionPerformed

    private void jmiNewAutomobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNewAutomobileActionPerformed
       JDialog frmAutomobile= new FrmAutomobile(this, true);
       frmAutomobile.setVisible(true);
    }//GEN-LAST:event_jmiNewAutomobileActionPerformed

    private void jmiShowAllCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowAllCustomersActionPerformed

    }//GEN-LAST:event_jmiShowAllCustomersActionPerformed

    private void jMenuAutomobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAutomobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAutomobileActionPerformed

    private void jmiShowAllAutomobilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowAllAutomobilesActionPerformed
        JDialog frmViewAutomobile = new FrmViewAutomobile(this, true);
        frmViewAutomobile.setVisible(true);
    }//GEN-LAST:event_jmiShowAllAutomobilesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAutomobile;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuCustomer;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmiNewAutomobile;
    private javax.swing.JMenuItem jmiNewCustomer;
    private javax.swing.JMenuItem jmiShowAllAutomobiles;
    private javax.swing.JMenuItem jmiShowAllCustomers;
    private javax.swing.JLabel lblLoggedUser;
    private javax.swing.JLabel lblSuccesfulLoginMessage;
    private javax.swing.JLabel lblimgHolder;
    private javax.swing.JTextField txtLoggedUser;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        setLocationRelativeTo(null);
        
        txtLoggedUser.setText(Controller.getInstance().getLoggedSeller().getFirstNname()+" "+ Controller.getInstance().getLoggedSeller().getLastName()+"");
    }
}
