/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ps.project.view.form;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ps.project.controller.Controller;
import ps.project.domain.Automobile;
import ps.project.main.view.form.component.table.AutomobileTableModel;

/**
 *
 * @author saska
 */
public class FrmViewAutomobile extends javax.swing.JDialog {

    /**
     * Creates new form FrmAutomobileView
     */
    public FrmViewAutomobile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutomobiles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz automobila");

        tblAutomobiles.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblAutomobiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Model", "Zapremina motora", "Snaga motora", "Cena sa PDV-om", "Cena bez PDV-a", "Karoserija", "Gorivo", "Valuta"
            }
        ));
        jScrollPane1.setViewportView(tblAutomobiles);

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pepareView() {
        setLocationRelativeTo(null);
//        fillTblAutomobiles();
        //  fillTblAutomobilesTM();
    }
    
   /* private void fillTblAutomobiles(){
       // List<Automobile> automobiles= Controller.getInstance().getAllAutomobiles();
        
        DefaultTableModel model = (DefaultTableModel) tblAutomobiles.getModel();
        for (Automobile automobile : automobiles) {
            Object[] rowData= new Object[] {
                automobile.getAutomobileId(),
                automobile.getModelId(),
                automobile.getCubicCapacity(),
                automobile.getEnginePower(),
                automobile.getPriceWithWat(),
                automobile.getPriceWithoutWat(),
                automobile.getVechileType(),
                automobile.getFuel(),
                automobile.getCurrency()};
                    
            model.addRow(rowData);
                   
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutomobiles;
    // End of variables declaration//GEN-END:variables

   /* private void fillTblAutomobilesTM() {
        List<Automobile> automobiles= Controller.getInstance().getAllAutomobiles();
        AutomobileTableModel atm= new AutomobileTableModel(automobiles);
        tblAutomobiles.setModel(atm);
    }*/
}
